In [1]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("customer_data.csv")

In [4]:
df.head()

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15,Resolved
1,2,NaN,Billing,30,Unresolved
2,3,2024-01-17,Technical,NaN,Resolved
3,4,2024-01-18,Account,10,Resolved
4,5,2024-01-19,Technical,60,Unresolved

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          50 non-null     int64
 1   date_of_interaction  49 non-null     object
 2   issue_category       50 non-null     object
 3   time_spent_minutes   46 non-null     object
 4   resolution_status    50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [7]:
df.isnull().sum()

customer_id            0
date_of_interaction    1
issue_category         0
time_spent_minutes     4
resolution_status      0
dtype: int64

In [11]:
df

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15,Resolved
1,2,NaN,Billing,30,Unresolved
2,3,2024-01-17,Technical,NaN,Resolved
3,4,2024-01-18,Account,10,Resolved
4,5,2024-01-19,Technical,60,Unresolved
5,6,2024-01-20,Billing,NaN,Resolved
6,7,2024-01-21,Support,35,Resolved
7,8,2024-01-22,Billing,25,Unresolved
8,9,2024-01-23,Technical,50,Resolved
9,10,2024-01-24,Account,5,Resolved
10,11,2024-01-25,Support,40,Resolved
11,12,2024-01-26,Technical,55,Unresolved
12,13,2024-01-27,Account,30,Resolved
13,14,2024-01-28,Billing,45,Resolved
14,15,2024-01-29,Support,60,Unresolved
15,16,2024-01-30,Technical,10,Resolved
16,17,2024-01-31,Billing,20,Unresolved
17,18,2024-02-01,Support,35,Resolved
18,19,2024-02-02,Account,15,Unresolved
19,20,2024-02-03,Technical,25,Resolved
20,21,2024-02-04,Billing,30,Resolved
21,22,2024-02-05,Account,40,Unresolved
22,23,2024-02-06,Support,NaN,Resolved
23,24,2024-02-07,Technical,50,Resolved
24,25,2024-02-08,Billing,20,Unresolved
25,26,2024-02-09,Account,15,Resolved
26,27,2024-02-10,Support,30,Resolved
27,28,2024-02-11,Technical,150,Unresolved
28,29,2024-02-12,Billing,10,Resolved
29,30,2024-02-13,Account,55,Unresolved
30,31,2024-02-14,Technical,15,Resolved
31,32,2024-02-15,Billing,20,Resolved
32,33,2024-02-16,Support,25,Resolved
33,34,2024-02-17,Technical,35,Unresolved
34,35,2024-02-18,Billing,50,Resolved
35,36,2024-02-19,Account,5,Unresolved
36,37,2024-02-20,Support,40,Resolved
37,38,2024-02-21,Technical,15,Resolved
38,39,2024-02-22,Billing,60,Unresolved
39,40,2024-02-23,Account,25,Resolved
40,41,2024-02-24,Support,10,Resolved
41,42,2024-02-25,Billing,30,Unresolved
42,43,2024-02-26,Technical,20,Resolved
43,44,2024-02-27,Support,15,Resolved
44,45,2024-02-28,Billing,40,Unresolved
45,46,2024-02-29,Account,NaN,Resolved
46,47,2024-03-01,Technical,30,Unresolved
47,48,2024-03-02,Billing,25,Resolved
48,49,2024-03-03,Support,50,Resolved
49,50,2024-03-04,Account,45,Unresolved

In [19]:
# I will create a dictionary with the numbers that are written as words
dict_str_to_int = {'forty':40, 'thirty':30}
df["time_spent_minutes"] = df["time_spent_minutes"].apply(lambda x: dict_str_to_int[x] if isinstance(x, str) and x in dict_str_to_int else x)
df

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15,Resolved
1,2,NaN,Billing,30,Unresolved
2,3,2024-01-17,Technical,NaN,Resolved
3,4,2024-01-18,Account,10,Resolved
4,5,2024-01-19,Technical,60,Unresolved
5,6,2024-01-20,Billing,NaN,Resolved
6,7,2024-01-21,Support,35,Resolved
7,8,2024-01-22,Billing,25,Unresolved
8,9,2024-01-23,Technical,50,Resolved
9,10,2024-01-24,Account,5,Resolved
10,11,2024-01-25,Support,40,Resolved
11,12,2024-01-26,Technical,55,Unresolved
12,13,2024-01-27,Account,30,Resolved
13,14,2024-01-28,Billing,45,Resolved
14,15,2024-01-29,Support,60,Unresolved
15,16,2024-01-30,Technical,10,Resolved
16,17,2024-01-31,Billing,20,Unresolved
17,18,2024-02-01,Support,35,Resolved
18,19,2024-02-02,Account,15,Unresolved
19,20,2024-02-03,Technical,25,Resolved
20,21,2024-02-04,Billing,30,Resolved
21,22,2024-02-05,Account,40,Unresolved
22,23,2024-02-06,Support,NaN,Resolved
23,24,2024-02-07,Technical,50,Resolved
24,25,2024-02-08,Billing,20,Unresolved
25,26,2024-02-09,Account,15,Resolved
26,27,2024-02-10,Support,30,Resolved
27,28,2024-02-11,Technical,150,Unresolved
28,29,2024-02-12,Billing,10,Resolved
29,30,2024-02-13,Account,55,Unresolved
30,31,2024-02-14,Technical,15,Resolved
31,32,2024-02-15,Billing,20,Resolved
32,33,2024-02-16,Support,25,Resolved
33,34,2024-02-17,Technical,35,Unresolved
34,35,2024-02-18,Billing,50,Resolved
35,36,2024-02-19,Account,5,Unresolved
36,37,2024-02-20,Support,40,Resolved
37,38,2024-02-21,Technical,15,Resolved
38,39,2024-02-22,Billing,60,Unresolved
39,40,2024-02-23,Account,25,Resolved
40,41,2024-02-24,Support,10,Resolved
41,42,2024-02-25,Billing,30,Unresolved
42,43,2024-02-26,Technical,20,Resolved
43,44,2024-02-27,Support,15,Resolved
44,45,2024-02-28,Billing,40,Unresolved
45,46,2024-02-29,Account,NaN,Resolved
46,47,2024-03-01,Technical,30,Unresolved
47,48,2024-03-02,Billing,25,Resolved
48,49,2024-03-03,Support,50,Resolved
49,50,2024-03-04,Account,45,Unresolved

In [26]:
df["time_spent_minutes"]  = df["time_spent_minutes"].astype(float)

mean = df["time_spent_minutes"].mean()
df["time_spent_minutes"] = df["time_spent_minutes"].fillna(value = mean)
df["time_spent_minutes"]

0      15.000000
1      30.000000
2      33.043478
3      10.000000
4      60.000000
5      33.043478
6      35.000000
7      25.000000
8      50.000000
9       5.000000
10     40.000000
11     55.000000
12     30.000000
13     45.000000
14     60.000000
15     10.000000
16     20.000000
17     35.000000
18     15.000000
19     25.000000
20     30.000000
21     40.000000
22     33.043478
23     50.000000
24     20.000000
25     15.000000
26     30.000000
27    150.000000
28     10.000000
29     55.000000
30     15.000000
31     20.000000
32     25.000000
33     35.000000
34     50.000000
35      5.000000
36     40.000000
37     15.000000
38     60.000000
39     25.000000
40     10.000000
41     30.000000
42     20.000000
43     15.000000
44     40.000000
45     33.043478
46     30.000000
47     25.000000
48     50.000000
49     45.000000
Name: time_spent_minutes, dtype: float64

In [29]:
#let's convert it to 2 decimal places
df["time_spent_minutes"] = df["time_spent_minutes"].round(2)

In [30]:
df

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15.00,Resolved
1,2,NaN,Billing,30.00,Unresolved
2,3,2024-01-17,Technical,33.04,Resolved
3,4,2024-01-18,Account,10.00,Resolved
4,5,2024-01-19,Technical,60.00,Unresolved
5,6,2024-01-20,Billing,33.04,Resolved
6,7,2024-01-21,Support,35.00,Resolved
7,8,2024-01-22,Billing,25.00,Unresolved
8,9,2024-01-23,Technical,50.00,Resolved
9,10,2024-01-24,Account,5.00,Resolved
10,11,2024-01-25,Support,40.00,Resolved
11,12,2024-01-26,Technical,55.00,Unresolved
12,13,2024-01-27,Account,30.00,Resolved
13,14,2024-01-28,Billing,45.00,Resolved
14,15,2024-01-29,Support,60.00,Unresolved
15,16,2024-01-30,Technical,10.00,Resolved
16,17,2024-01-31,Billing,20.00,Unresolved
17,18,2024-02-01,Support,35.00,Resolved
18,19,2024-02-02,Account,15.00,Unresolved
19,20,2024-02-03,Technical,25.00,Resolved
20,21,2024-02-04,Billing,30.00,Resolved
21,22,2024-02-05,Account,40.00,Unresolved
22,23,2024-02-06,Support,33.04,Resolved
23,24,2024-02-07,Technical,50.00,Resolved
24,25,2024-02-08,Billing,20.00,Unresolved
25,26,2024-02-09,Account,15.00,Resolved
26,27,2024-02-10,Support,30.00,Resolved
27,28,2024-02-11,Technical,150.00,Unresolved
28,29,2024-02-12,Billing,10.00,Resolved
29,30,2024-02-13,Account,55.00,Unresolved
30,31,2024-02-14,Technical,15.00,Resolved
31,32,2024-02-15,Billing,20.00,Resolved
32,33,2024-02-16,Support,25.00,Resolved
33,34,2024-02-17,Technical,35.00,Unresolved
34,35,2024-02-18,Billing,50.00,Resolved
35,36,2024-02-19,Account,5.00,Unresolved
36,37,2024-02-20,Support,40.00,Resolved
37,38,2024-02-21,Technical,15.00,Resolved
38,39,2024-02-22,Billing,60.00,Unresolved
39,40,2024-02-23,Account,25.00,Resolved
40,41,2024-02-24,Support,10.00,Resolved
41,42,2024-02-25,Billing,30.00,Unresolved
42,43,2024-02-26,Technical,20.00,Resolved
43,44,2024-02-27,Support,15.00,Resolved
44,45,2024-02-28,Billing,40.00,Unresolved
45,46,2024-02-29,Account,33.04,Resolved
46,47,2024-03-01,Technical,30.00,Unresolved
47,48,2024-03-02,Billing,25.00,Resolved
48,49,2024-03-03,Support,50.00,Resolved
49,50,2024-03-04,Account,45.00,Unresolved

In [31]:
df.isnull().sum()

customer_id            0
date_of_interaction    1
issue_category         0
time_spent_minutes     0
resolution_status      0
dtype: int64

In [42]:
#now let's drop the row where date of interaction is not availible since it's just one
df.dropna(subset = ["date_of_interaction"], inplace = True)
df.head()

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15.00,Resolved
2,3,2024-01-17,Technical,33.04,Resolved
3,4,2024-01-18,Account,10.00,Resolved
4,5,2024-01-19,Technical,60.00,Unresolved
5,6,2024-01-20,Billing,33.04,Resolved

In [43]:
df.isnull().sum()

customer_id            0
date_of_interaction    0
issue_category         0
time_spent_minutes     0
resolution_status      0
dtype: int64

In [44]:
df["date_of_interaction"] = pd.to_datetime(df["date_of_interaction"])

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          49 non-null     int64
 1   date_of_interaction  49 non-null     datetime64[ns]
 2   issue_category       49 non-null     object
 3   time_spent_minutes   49 non-null     float64
 4   resolution_status    49 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 2.3+ KB

In [46]:
df.head()

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status
0,1,2024-01-15,Account,15.00,Resolved
2,3,2024-01-17,Technical,33.04,Resolved
3,4,2024-01-18,Account,10.00,Resolved
4,5,2024-01-19,Technical,60.00,Unresolved
5,6,2024-01-20,Billing,33.04,Resolved

In [52]:
df['day_of_week'] = df['date_of_interaction'].dt.day_name()

In [53]:
df

,customer_id,date_of_interaction,issue_category,time_spent_minutes,resolution_status,day_of_week
0,1,2024-01-15,Account,15.00,Resolved,Monday
2,3,2024-01-17,Technical,33.04,Resolved,Wednesday
3,4,2024-01-18,Account,10.00,Resolved,Thursday
4,5,2024-01-19,Technical,60.00,Unresolved,Friday
5,6,2024-01-20,Billing,33.04,Resolved,Saturday
6,7,2024-01-21,Support,35.00,Resolved,Sunday
7,8,2024-01-22,Billing,25.00,Unresolved,Monday
8,9,2024-01-23,Technical,50.00,Resolved,Tuesday
9,10,2024-01-24,Account,5.00,Resolved,Wednesday
10,11,2024-01-25,Support,40.00,Resolved,Thursday
11,12,2024-01-26,Technical,55.00,Unresolved,Friday
12,13,2024-01-27,Account,30.00,Resolved,Saturday
13,14,2024-01-28,Billing,45.00,Resolved,Sunday
14,15,2024-01-29,Support,60.00,Unresolved,Monday
15,16,2024-01-30,Technical,10.00,Resolved,Tuesday
16,17,2024-01-31,Billing,20.00,Unresolved,Wednesday
17,18,2024-02-01,Support,35.00,Resolved,Thursday
18,19,2024-02-02,Account,15.00,Unresolved,Friday
19,20,2024-02-03,Technical,25.00,Resolved,Saturday
20,21,2024-02-04,Billing,30.00,Resolved,Sunday
21,22,2024-02-05,Account,40.00,Unresolved,Monday
22,23,2024-02-06,Support,33.04,Resolved,Tuesday
23,24,2024-02-07,Technical,50.00,Resolved,Wednesday
24,25,2024-02-08,Billing,20.00,Unresolved,Thursday
25,26,2024-02-09,Account,15.00,Resolved,Friday
26,27,2024-02-10,Support,30.00,Resolved,Saturday
27,28,2024-02-11,Technical,150.00,Unresolved,Sunday
28,29,2024-02-12,Billing,10.00,Resolved,Monday
29,30,2024-02-13,Account,55.00,Unresolved,Tuesday
30,31,2024-02-14,Technical,15.00,Resolved,Wednesday
31,32,2024-02-15,Billing,20.00,Resolved,Thursday
32,33,2024-02-16,Support,25.00,Resolved,Friday
33,34,2024-02-17,Technical,35.00,Unresolved,Saturday
34,35,2024-02-18,Billing,50.00,Resolved,Sunday
35,36,2024-02-19,Account,5.00,Unresolved,Monday
36,37,2024-02-20,Support,40.00,Resolved,Tuesday
37,38,2024-02-21,Technical,15.00,Resolved,Wednesday
38,39,2024-02-22,Billing,60.00,Unresolved,Thursday
39,40,2024-02-23,Account,25.00,Resolved,Friday
40,41,2024-02-24,Support,10.00,Resolved,Saturday
41,42,2024-02-25,Billing,30.00,Unresolved,Sunday
42,43,2024-02-26,Technical,20.00,Resolved,Monday
43,44,2024-02-27,Support,15.00,Resolved,Tuesday
44,45,2024-02-28,Billing,40.00,Unresolved,Wednesday
45,46,2024-02-29,Account,33.04,Resolved,Thursday
46,47,2024-03-01,Technical,30.00,Unresolved,Friday
47,48,2024-03-02,Billing,25.00,Resolved,Saturday
48,49,2024-03-03,Support,50.00,Resolved,Sunday
49,50,2024-03-04,Account,45.00,Unresolved,Monday

In [57]:
import sklearn
from sklearn.model_selection import train_test_split

In [59]:
features = df.drop(columns = ['resolution_status'])
status = df['resolution_status']
x_train, x_test, y_train, y_test = train_test_split(features, status, test_size = 0.2)